services:
  # Traefik reverse proxy - handles HTTPS and routing
  traefik:
    image: traefik:v3
    container_name: stratdyn-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=paul.grogan@asu.edu
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=false
    restart: unless-stopped
    networks:
      - stratdyn-network

  stratdyn:
    build: .
    container_name: stratdyn-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Mount data directory to persist experiment data
      - ./data:/app/data
      # Mount logs directory to persist CSV logs
      - ./logs:/app/logs
    networks:
      - stratdyn-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.stratdyn.rule=Host(`game.code-lab.org`)
      - traefik.http.services.stratdyn.loadbalancer.server.port=3000

networks:
  stratdyn-network:
    driver: bridge

volumes:
  letsencrypt:
